[package]
name = "jwatch"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
indicatif = "0.18.0"
rusqlite = "0.37.0"
time = { version = "0.3.44", features = ["local-offset"] }
walkdir = "2.5.0"
